version: "3"
services:
    nginx_service:
        build: 
          context: web
        volumes:
          - ./web/nginx_conf:/etc/nginx/conf.d                
        ports:
          - 80:80
        networks:
            api_net:
                ipv4_address: 172.19.10.2         
        depends_on:
          - flask_service

    flask_service:
        build:
          context: backend    
        networks:
            api_net:
                ipv4_address: 172.19.10.3                      
        env_file:
          - .env
        depends_on:
            - postgres_service
       
    postgres_service:
        image: postgres:12.0-alpine
        stdin_open: true
        tty: true
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
          - .env      
        networks:
            api_net:
                ipv4_address: 172.19.10.4

volumes:
    postgres_data:
   
networks:
    api_net:
        ipam:
            driver: default
            config:
                - subnet: 172.19.10.0/29  


